// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeMapQROOBackend.Data;

#nullable disable

namespace SafeMapQROOBackend.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "013dd9ab-4f42-425a-bceb-e8a9e37bf801",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "c41a464e-2834-43b3-9b58-a0cc20324236",
                            Name = "Organizer",
                            NormalizedName = "ORGANIZER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SafeMapQROOBackend.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AssignedShelter")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SafeMapQROOBackend.Models.Occupancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShelterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("Occupancy");
                });

            modelBuilder.Entity("SafeMapQROOBackend.Models.Shelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("Municipality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shelter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16636e02-e226-4cb5-bea8-dccbf99582a8"),
                            Address = "Celul Entre Chicozapote Y 30 De Noviembre",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.495383653994043,
                            Longitude = -88.294683737312042,
                            Municipality = 3,
                            Name = "Eva Sámano De López Mateos"
                        },
                        new
                        {
                            Id = new Guid("053b4b1d-9c99-4c7f-ba4f-d40c9d071c6f"),
                            Address = "Av. Chetumal S/N Entre Dos Aguadas Y Subteniente López",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.527211107161367,
                            Longitude = -88.300609758892449,
                            Municipality = 3,
                            Name = "Esc. Sec. Armando Escobar Nava"
                        },
                        new
                        {
                            Id = new Guid("cc4b5b08-9ae7-4f37-8697-90123ea286e3"),
                            Address = "Calle Noh Bec/Laguna San Felipe Y Xul-ha",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.519882569200256,
                            Longitude = -88.335114092623812,
                            Municipality = 3,
                            Name = "Esc. Primaria Guadalupe Victoria"
                        },
                        new
                        {
                            Id = new Guid("185cd024-abbb-4cdf-a9b5-61672e4547b2"),
                            Address = "Av. Insurgentes S/N Km. 6",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.515370467529763,
                            Longitude = -88.352859371161458,
                            Municipality = 3,
                            Name = "CBTA 11"
                        },
                        new
                        {
                            Id = new Guid("ec54c54e-5db4-47c3-9d82-38c7e54925df"),
                            Address = "C. Emiliano Zapata S/N, Entre Carranza Y Primo De Verdad.",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.506674340398099,
                            Longitude = -88.301716254010174,
                            Municipality = 3,
                            Name = "Escuela Primaria Francisco I. Madero"
                        },
                        new
                        {
                            Id = new Guid("74ae6db3-4fe7-483d-b8c5-db59db0f2a5a"),
                            Address = "Calle 3 S/N Esq. Av. Chetumal",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.533446028131031,
                            Longitude = -88.302344235527571,
                            Municipality = 3,
                            Name = "Escuela Primaria Francisco Primo De Verdad"
                        },
                        new
                        {
                            Id = new Guid("8a56e722-d982-4ffb-86c9-fb525bcaa487"),
                            Address = "Sacxan Entre Raudales Y Tres Garantías",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.526339797397608,
                            Longitude = -88.305566276683464,
                            Municipality = 3,
                            Name = "CBTIS 253"
                        },
                        new
                        {
                            Id = new Guid("38888ca2-8f15-49cd-aeec-dc1ca6e8995f"),
                            Address = "Av. Heriberto Frías No. 562 Esquina Cedro Y Siricote",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.525705291267954,
                            Longitude = -88.275477806131235,
                            Municipality = 3,
                            Name = "CBTIS 214"
                        },
                        new
                        {
                            Id = new Guid("3b752bff-8ffc-4e8f-a3bc-56bd10f819e3"),
                            Address = "Avenida 19a entre calles 38 Y 40",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.689105215437817,
                            Longitude = -88.39290885520002,
                            Municipality = 9,
                            Name = "Sec. Tec. Ernesto Novelo y Novelo"
                        },
                        new
                        {
                            Id = new Guid("6a17f2cb-085f-4377-83db-c159692f3dc9"),
                            Address = "Avenida 5 entre calles 12 Y 14",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.673971341456461,
                            Longitude = -88.392410168081128,
                            Municipality = 9,
                            Name = "Escuela Primaria Rafael Ramírez Castañeda"
                        },
                        new
                        {
                            Id = new Guid("735e6d8a-320f-4be7-ae40-57a6c301a4c1"),
                            Address = "Calle 14 entre avenidas 7 Y 9",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.674963588205589,
                            Longitude = -88.394058247230561,
                            Municipality = 9,
                            Name = "Esc. Sec. Fed. Vicente Guerrero"
                        },
                        new
                        {
                            Id = new Guid("37dd9787-b186-4e69-b504-2117f966d743"),
                            Address = "Calle 12 entre avenida 9 Y 9ª",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 9,
                            Name = "Jardín de Niños Laguna De Bacalar"
                        },
                        new
                        {
                            Id = new Guid("f613793a-106f-4f45-a63c-6f64f9458a6d"),
                            Address = "Av. 9 con calle 20",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.677992165641122,
                            Longitude = -88.392907660079146,
                            Municipality = 9,
                            Name = "Casa del Adulto Mayor"
                        },
                        new
                        {
                            Id = new Guid("de97a8c7-c7db-4018-9c90-d0f5058d90ed"),
                            Address = "Calle 4 con Av. 19 C",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 18.677695316042485,
                            Longitude = -88.392950699837371,
                            Municipality = 9,
                            Name = "Comedor Comunitario"
                        },
                        new
                        {
                            Id = new Guid("f1fca176-c51d-40ba-a046-59790d1cf8ca"),
                            Address = "Calle Mercurio",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.207555286203757,
                            Longitude = -87.465820152086536,
                            Municipality = 8,
                            Name = "Escuela Primaria 'Julio Ruelas' TM / TV"
                        },
                        new
                        {
                            Id = new Guid("f2759cf4-b715-46fa-86d0-973920f3c1d8"),
                            Address = "Calle Júpiter Sur",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.209647664177151,
                            Longitude = -87.465278841651966,
                            Municipality = 8,
                            Name = "Escuela Telesecundaria 'Erick Paolo Martínez' TM / TV"
                        },
                        new
                        {
                            Id = new Guid("50fc1679-a3c9-4d1f-8b24-c31e72467da1"),
                            Address = "Calle Mercurio",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.208293327631974,
                            Longitude = -87.457320476622229,
                            Municipality = 8,
                            Name = "Escuela Primaria 'Ford 198' T.M Y T.V."
                        },
                        new
                        {
                            Id = new Guid("40650a4e-4a8e-4701-a82c-b435b8cecb55"),
                            Address = "Calle Osiris",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.213708964239601,
                            Longitude = -87.463117206069768,
                            Municipality = 8,
                            Name = "Escuela Primaria 'Octaviano Solís Aguirre' T.M Y T.V."
                        },
                        new
                        {
                            Id = new Guid("391723ca-e804-445c-814a-2bafc9e5277c"),
                            Address = "Venustiano Carranza Chiapas CP. 30170",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.213710222746002,
                            Longitude = -87.463116535517528,
                            Municipality = 8,
                            Name = "Escuela Secundaria Federal #15 'Zamna' TM / TV"
                        },
                        new
                        {
                            Id = new Guid("808b0eec-37da-4f08-bd48-8bc1d5af4329"),
                            Address = "Calle Bojon",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.217173432508588,
                            Longitude = -87.471662750121681,
                            Municipality = 8,
                            Name = "Escuela Primaria 'Gregorio Pérez Cahuich' TM / TV"
                        },
                        new
                        {
                            Id = new Guid("fa7c249a-f85a-42f4-bcd0-341ec09168ff"),
                            Address = "Calle Sax kin",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 8,
                            Name = "Escuela Primaria 'Tulum' TM / TV"
                        },
                        new
                        {
                            Id = new Guid("80ec9b6c-9ccc-40e3-87de-9ed366843f32"),
                            Address = "Calle Alfa entre calle 4 Oriente",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.214037722418862,
                            Longitude = -87.464550646103504,
                            Municipality = 8,
                            Name = "Instituto de Capacitación para el Trabajo de TULUM (ICAT)"
                        },
                        new
                        {
                            Id = new Guid("8a7fc629-8d8e-49a4-bdf7-18f41398bffd"),
                            Address = "Lote 001 Mza. 05-06 Región 13",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.205983223350799,
                            Longitude = -87.505270994412811,
                            Municipality = 8,
                            Name = "Universidad tecnológica de Tulum"
                        },
                        new
                        {
                            Id = new Guid("e6108dbc-db8c-40b9-8642-21cc95df25f0"),
                            Address = "Calle 4 Ote",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.213798798263635,
                            Longitude = -87.464981853920406,
                            Municipality = 8,
                            Name = "CECYTE Plantel Tulum"
                        },
                        new
                        {
                            Id = new Guid("705f8cc2-6a71-44c9-a30f-f7b365829fe6"),
                            Address = "Calle 80 Entre 61 Y 67 De La Colonia Francisco May",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.575971504298611,
                            Longitude = -88.038594406093679,
                            Municipality = 1,
                            Name = "Esc. Sec. Tec. José María Luis Mora"
                        },
                        new
                        {
                            Id = new Guid("dc033e06-35ed-4b47-90dc-6294bf986e88"),
                            Address = "Calle 66 Entre 69 Y Av. Lázaro Cárdenas #783, Col. Centro",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.579954512625008,
                            Longitude = -88.045826637392167,
                            Municipality = 1,
                            Name = "Esc. Prim. Moisés Sáenz"
                        },
                        new
                        {
                            Id = new Guid("2f1440b6-ca36-413f-af33-2edd9d582210"),
                            Address = "Av. Constituyentes Entre 89 Y 91, Col. Emiliano Zapata",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 1,
                            Name = "Centro De Estudios De Bachillerato Rafael Ramírez Castañeda"
                        },
                        new
                        {
                            Id = new Guid("fe39670c-14fa-4d19-9cbf-4f8b08d6f921"),
                            Address = "Calle 60 Por Calle 77 Y 79, Col. Leona Vicario",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.585141347295604,
                            Longitude = -88.048711057034055,
                            Municipality = 1,
                            Name = "Esc. Prim. Don Felipe Carrillo Puerto"
                        },
                        new
                        {
                            Id = new Guid("f94e8d35-7eb4-4b02-b2ac-b23efae7028d"),
                            Address = "Av. Lázaro Cárdenas #117 Por Calle 56 Y 60 Col. Cecilio Chi",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.581909388815529,
                            Longitude = -88.049994505740557,
                            Municipality = 1,
                            Name = "Esc. Sec. Leona Vicario"
                        },
                        new
                        {
                            Id = new Guid("63d838f5-ba09-4447-8cd2-6e53a7b0f43a"),
                            Address = "Calle 55 Entre 50-a Y 52, Col Lázaro Cárdenas",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 1,
                            Name = "Escuela De Educación Especial"
                        },
                        new
                        {
                            Id = new Guid("5a275d60-163e-4aeb-b3dd-c903aa1bab05"),
                            Address = "Calle 30 Entre 75 Y 73 Col. Plan De Ayala",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.588223146043042,
                            Longitude = -88.064325641746109,
                            Municipality = 1,
                            Name = "Plantel Conalep"
                        },
                        new
                        {
                            Id = new Guid("221f3b8d-a40d-46c2-8aaf-a7457f938096"),
                            Address = "Reg. 17, Mza 36, Lt. 1 y 2 Calle Caoba",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.85053567421069,
                            Longitude = -86.903969030582246,
                            Municipality = 10,
                            Name = "Colegio De Bachilleres Pto. Morelos"
                        },
                        new
                        {
                            Id = new Guid("99de916b-2dd1-4d78-b25e-06626cb65f56"),
                            Address = "Calle Caoba",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.856127570497915,
                            Longitude = -86.902564042238737,
                            Municipality = 10,
                            Name = "Telesecundaria 'Ramon Bravo Prieto'"
                        },
                        new
                        {
                            Id = new Guid("f20090a1-cc86-4f30-b142-d4bac72a4a69"),
                            Address = "Colonia La Granja",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.994028250826879,
                            Longitude = -87.211871843233396,
                            Municipality = 10,
                            Name = "Yucatán Península Misión"
                        },
                        new
                        {
                            Id = new Guid("12d5c73b-4ca1-46f1-b1dd-a284376bcf61"),
                            Address = "Mza. 177, Lt. 3, Zona 1, Población Leona Vicario, Puerto Morelos",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.994820791715942,
                            Longitude = -87.206637911723405,
                            Municipality = 10,
                            Name = "Iglesia Ríos De Dios"
                        },
                        new
                        {
                            Id = new Guid("c28535ae-3d92-4f31-83c8-70ccadeb536b"),
                            Address = "Reg. 236 Mza. 24 Lote 33",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.201405877622058,
                            Longitude = -86.835542309713418,
                            Municipality = 4,
                            Name = "Año Del Centenario De Q.Roo"
                        },
                        new
                        {
                            Id = new Guid("2012d99b-3cbe-4941-99ee-3396a7be11a9"),
                            Address = "SM 247 Mza. 13 LT 3 Villas Otoch 2ª Etapa",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.197140865657754,
                            Longitude = -86.86050333123444,
                            Municipality = 4,
                            Name = "Miguel Hidalgo Y Costilla"
                        },
                        new
                        {
                            Id = new Guid("2159fa19-da16-4a04-bff9-2b7d8a6fe28f"),
                            Address = "SM 247 Mza. 33 Villas Otoch 3ª Etapa",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.200463843722158,
                            Longitude = -86.853726557029603,
                            Municipality = 4,
                            Name = "Escuela Primaria Ek Balam"
                        },
                        new
                        {
                            Id = new Guid("172d800b-d236-4272-b3be-2fb3e3381e6b"),
                            Address = "259 Mza. 40 Las Palmas",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.15781363698234,
                            Longitude = -86.913879790078084,
                            Municipality = 4,
                            Name = "Amado Nervo"
                        },
                        new
                        {
                            Id = new Guid("42efa095-a1da-4d2c-8288-7ffae24bc2f0"),
                            Address = "Calle Efraín Pineda Sn Col. 3 Reyes",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.110266227473048,
                            Longitude = -86.945734494307175,
                            Municipality = 4,
                            Name = "Otilio Montaño"
                        },
                        new
                        {
                            Id = new Guid("da9c5718-2686-4611-a94e-35f4b3fa0101"),
                            Address = "Av. Luis Echeverria Con Salinas De Gortari",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.089886339335585,
                            Longitude = -86.85703588333395,
                            Municipality = 4,
                            Name = "Bachilleres 3"
                        },
                        new
                        {
                            Id = new Guid("cec8cbbd-91a8-447c-8522-d252546145d2"),
                            Address = "Entre 27 Y 31 Sur",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.491025387279585,
                            Longitude = -86.954710406055867,
                            Municipality = 0,
                            Name = "Colegio De Bachilleres"
                        },
                        new
                        {
                            Id = new Guid("b966fa02-d2b2-4a9f-ae6b-a48e27a07bb3"),
                            Address = "Sin Cruzamientos",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.4865903108536,
                            Longitude = -86.943468600511522,
                            Municipality = 0,
                            Name = "Centro De Estudio Tecnológico Del Mar 33"
                        },
                        new
                        {
                            Id = new Guid("ee162152-451e-4b7e-86a6-d173feb52ffc"),
                            Address = "Entre Calles Coral Y Delfín",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.487221935756299,
                            Longitude = -86.925994447775636,
                            Municipality = 0,
                            Name = "Esc. Sec. Carlos Monsiváis"
                        },
                        new
                        {
                            Id = new Guid("0f2e7997-5e92-45cf-8bf0-6ed2f0b13a88"),
                            Address = "Entre 21 Y 23 Sur",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.496017048999189,
                            Longitude = -86.954384145423958,
                            Municipality = 0,
                            Name = "Conalep"
                        },
                        new
                        {
                            Id = new Guid("ebf6d083-4f60-4563-bf13-407ad2f8106a"),
                            Address = "Entre 35 Y 37 Sur",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.482103327599656,
                            Longitude = -86.952134442252998,
                            Municipality = 0,
                            Name = "Esc. Sec. Octavio Paz"
                        },
                        new
                        {
                            Id = new Guid("3c8b0fdc-9c08-4c18-ba2c-5c45f0566e5b"),
                            Address = "Calle Cherna Col. La Gloria, Isla Mujeres, Isla Mujeres, Quintana Roo C.P. 77402",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 2,
                            Name = "Sindicato Único Para Los Trabajadores Al Servicio Del Ayto. De Isla Mujeres"
                        },
                        new
                        {
                            Id = new Guid("4f634e3a-b2d5-41f6-9e54-203a23aa8bd9"),
                            Address = "Calle: Sierra, Sm: 006, Mza. 190, Lote: 011, Colonia La Gloria, Cp. 77400",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.225088455420973,
                            Longitude = -86.725707312776251,
                            Municipality = 2,
                            Name = "Escuela Primaria Julio Sauri Espinosa"
                        },
                        new
                        {
                            Id = new Guid("b78ed8d8-37ae-4165-b77c-5f8e1265c874"),
                            Address = "Calle: 2 Entre Calle: 40 Sur Y Calle: 38 Sur, El Centro Comunitario, Rancho Viejo, Centro Urbano.",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.22607331145349,
                            Longitude = -86.851489829327932,
                            Municipality = 2,
                            Name = "Centro Comunitario, Zona Continental"
                        },
                        new
                        {
                            Id = new Guid("997ffda5-0408-483e-9432-7f9db6767ef3"),
                            Address = "Francisco May",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 2,
                            Name = "Escuela Rural 'San Antonio' "
                        },
                        new
                        {
                            Id = new Guid("17192969-847f-49b4-860a-30bf5a7647d5"),
                            Address = "Francisco May",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 2,
                            Name = "Escuela Prescolar Comunitario"
                        },
                        new
                        {
                            Id = new Guid("c4a7bc83-a425-4236-a3fb-fd4cc1d7d0d3"),
                            Address = "Rancho Viejo, Centro Urbano",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 2,
                            Name = "Colegio De Bachilleres, Zona Continental"
                        },
                        new
                        {
                            Id = new Guid("dd72279a-bf37-4cc4-8a28-04af8547f544"),
                            Address = "Av. 135 Entre C. 1era Y 3 Sur, Col Bellavista",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.635912503977863,
                            Longitude = -87.100272452680386,
                            Municipality = 7,
                            Name = "Esc. Prim. Mario Chan Hoyos"
                        },
                        new
                        {
                            Id = new Guid("9aea0ffa-e1ec-41ab-aa6e-09fd9e5e0285"),
                            Address = "C. Almendro Esq. C. Alamo Alcaldía Puerto Aventuras",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.652396175212225,
                            Longitude = -87.059175859425949,
                            Municipality = 7,
                            Name = "Centro De Atención Al Migrante"
                        },
                        new
                        {
                            Id = new Guid("58d9c571-7e0e-46bd-afa0-ea0dbe4ab179"),
                            Address = "Av. 80 Esq. C26 Nte. Col. Ejido",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.636713863505857,
                            Longitude = -87.085735483351868,
                            Municipality = 7,
                            Name = "Esc. Sec. No. 23 Juan Rulfo"
                        },
                        new
                        {
                            Id = new Guid("178e50a5-38cc-45d2-aae5-6188e0bb7507"),
                            Address = "Av. 105 Entre C36 Y 38 Col. Pedregal",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.643717950964632,
                            Longitude = -87.087248854515764,
                            Municipality = 7,
                            Name = "Esc. Prim. José Fernandez De Lizardi"
                        },
                        new
                        {
                            Id = new Guid("a401cce6-3582-472c-9a2b-e0b3fa1d3ed8"),
                            Address = "Av. Xel-ha Esq. Corales Col. La Guadalupana",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.656533270672895,
                            Longitude = -87.116255523365282,
                            Municipality = 7,
                            Name = "Conalep"
                        },
                        new
                        {
                            Id = new Guid("e5412ed0-319f-4f64-9093-5192f25100e4"),
                            Address = "C. Trinidad Y Tobago Esq. Cancún Col. La Guadalupana",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.680611493774979,
                            Longitude = -87.046634566279153,
                            Municipality = 7,
                            Name = "Esc. Prim. Urb. Fed. Jaime Torres"
                        },
                        new
                        {
                            Id = new Guid("15cdc779-ec60-485b-9c61-b5dc4cc2fae8"),
                            Address = "C. Brasil entre Bolivia y Av. México Col. La Guadalupana",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.68549552680901,
                            Longitude = -87.056682441633626,
                            Municipality = 7,
                            Name = "Esc. Prim. Riviera Maya"
                        },
                        new
                        {
                            Id = new Guid("f4c825e4-e7ff-4eb5-b1aa-643ff2243f30"),
                            Address = "Eje de la Aurora Esq. Calzada del Sol Alcaldía Puerto Aventuras",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.686807193341103,
                            Longitude = -87.049751942954828,
                            Municipality = 7,
                            Name = "Esc. Prim. Luis Donaldo Colosio Murrieta"
                        },
                        new
                        {
                            Id = new Guid("7d04da73-166c-4169-aeff-81a60c682437"),
                            Address = "Av. Bosque de la Generosidad Col. Cristo Rey",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.708291805276215,
                            Longitude = -87.076227601752066,
                            Municipality = 7,
                            Name = "Esc. Prim. Constituyentes De 1974"
                        },
                        new
                        {
                            Id = new Guid("e17a7d1d-0951-4c94-92f6-77fe04f5ecab"),
                            Address = "C.88 entre Av. 20 Y 25 Col. Colosio",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.648489217384746,
                            Longitude = -87.060713131202036,
                            Municipality = 7,
                            Name = "Esc. Prim. Gregoria Cob Cob"
                        },
                        new
                        {
                            Id = new Guid("93c80f15-5602-4429-8731-2a45910fc7ea"),
                            Address = "Av. de las Cigüeñas Entre Av. Loros y Tórtolas Col. Villas Del Sol",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.66978836445206,
                            Longitude = -87.115752513029136,
                            Municipality = 7,
                            Name = "Esc. Prim. Independencia De México"
                        },
                        new
                        {
                            Id = new Guid("5b6b1c57-da93-4037-9029-815416ab430b"),
                            Address = "Av. Calzada del Sol Con Av. Calzada Puerto Maya Alcaldía Puerto Aventuras",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.510261328614845,
                            Longitude = -87.228414364750265,
                            Municipality = 7,
                            Name = "Esc. Sec. José A. Tzuc Esparza"
                        },
                        new
                        {
                            Id = new Guid("6a0a4b62-6e35-4233-8cc0-363e5eec09ea"),
                            Address = "Calle 15 entre Av. 130 y Av. 135 Col. Bellavista",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.632354656169483,
                            Longitude = -87.101567518903636,
                            Municipality = 7,
                            Name = "Esc. Prim. José González López Esquivel"
                        },
                        new
                        {
                            Id = new Guid("1d33879d-88bb-49c0-a6fe-cda36bb43cd8"),
                            Address = "Calle Xiat entre calle Copete y Calle Chicozapote Puerto Aventura",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.511676242860254,
                            Longitude = -87.234629812056696,
                            Municipality = 7,
                            Name = "Esc. Prim. Miguel Ortega Navarrete"
                        },
                        new
                        {
                            Id = new Guid("ff96b934-d876-4fb8-a643-9cc46c501eca"),
                            Address = "Calle Benito Juárez, Esq. 5 De Mayo",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.743748669434591,
                            Longitude = -88.711222558236713,
                            Municipality = 5,
                            Name = "Secundaria Lic. Andrés Q,Roo"
                        },
                        new
                        {
                            Id = new Guid("9582302a-7468-41ed-9089-616fb8454e7f"),
                            Address = "Calle Miguel Hidalgo, Col. Guadalupe",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.756444646455947,
                            Longitude = -88.701862272340605,
                            Municipality = 5,
                            Name = "Colegio De Bachilleres JMM"
                        },
                        new
                        {
                            Id = new Guid("735b50f3-2122-470d-84d4-164f092d6d18"),
                            Address = "Calle Benito Juárez Esquina Santiago Pacheco",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.748537443736431,
                            Longitude = -88.705841389488668,
                            Municipality = 5,
                            Name = "Esc. Primaria Benito Juárez"
                        },
                        new
                        {
                            Id = new Guid("76e5c86e-944f-4eff-9be1-cd759bec5fb7"),
                            Address = "Calle Benito Juárez Esq. 5 De Mayo Y Cecilio Chi",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.744573984323505,
                            Longitude = -88.71029053590398,
                            Municipality = 5,
                            Name = "Esc. Primaria Agustín Melgar"
                        },
                        new
                        {
                            Id = new Guid("6cdfc498-f90e-4569-825a-c5a88d252ca7"),
                            Address = "Calle Vicente Guerrero Y Kohunlich",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.749166908290125,
                            Longitude = -88.715845479087108,
                            Municipality = 5,
                            Name = "Esc. Primaria Carlos Lugo López"
                        },
                        new
                        {
                            Id = new Guid("0d2a0511-6fa6-49ad-a224-b6742b92ec23"),
                            Address = "C. 42 Constituyentes del 74 & C. 47 Santiago Pacheco, San Antonio Tuk, 77890",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 19.748410893884273,
                            Longitude = -88.705682018779243,
                            Municipality = 5,
                            Name = "Esc. Primaria Niños Héroes"
                        },
                        new
                        {
                            Id = new Guid("b2c89b0b-759a-4aa0-a204-bb0dc85b4aa7"),
                            Address = "Carretera Fed. Cancún-vallad",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.881945592688428,
                            Longitude = -87.532865450328828,
                            Municipality = 6,
                            Name = "Colegio de Bachilleres Plantel Ignacio Zaragoza"
                        },
                        new
                        {
                            Id = new Guid("052dc3df-88b3-4ae4-8033-23c19f5462ff"),
                            Address = "Km33 Carretera Ideal-Chiquilá",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.128569002243346,
                            Longitude = -87.483637323824993,
                            Municipality = 6,
                            Name = "Centro de Bachillerato Tecnológico Agropecuario No. 186"
                        },
                        new
                        {
                            Id = new Guid("e1553996-752e-4760-a68f-1e8a93245c1a"),
                            Address = "Reforma Agraria",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 21.10562743813621,
                            Longitude = -87.485876705139603,
                            Municipality = 6,
                            Name = "Kantunilkin"
                        },
                        new
                        {
                            Id = new Guid("871088c1-fe86-4b58-9bdb-f25310d75ab9"),
                            Address = "a 97700, C. 52-a 422, Adolfo López Mateos, Yuc.",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.12382850497012,
                            Longitude = -88.159538324053358,
                            Municipality = 6,
                            Name = "Jacinto Canek"
                        },
                        new
                        {
                            Id = new Guid("e8983888-50f1-4fa6-a820-0e1fb1dcfc96"),
                            Address = "Carr. Costera del Golfo 295, 77380 Nuevo Xcán, Q.R.",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 20.870816194387903,
                            Longitude = -87.602493388787138,
                            Municipality = 6,
                            Name = "Ramón Osorio Y Osorio"
                        },
                        new
                        {
                            Id = new Guid("160a0e43-37e8-44d4-a8b6-bfef3894bd3f"),
                            Address = "77333 San Ángel, Q.R.",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.233190656324986,
                            Longitude = -87.434847971671459,
                            Municipality = 6,
                            Name = "Telesecundaria 'Herminia Medina Loria'"
                        },
                        new
                        {
                            Id = new Guid("ad79289a-8ed9-420d-a91b-606f8dfb683b"),
                            Address = "Calle Agustín Melgar",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.351966506718576,
                            Longitude = -87.430164143462861,
                            Municipality = 6,
                            Name = "Secundaria Terencio Tah Quetzal"
                        },
                        new
                        {
                            Id = new Guid("3594c634-c8ce-487c-b5e0-6268b7249c6c"),
                            Address = "Calle Miguel Hidalgo",
                            Available = true,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Latitude = 21.10651575229522,
                            Longitude = -87.484958567773049,
                            Municipality = 6,
                            Name = "Albergue 'Benito Juárez'"
                        },
                        new
                        {
                            Id = new Guid("323047d3-3914-488e-a0fb-7077401b9495"),
                            Address = "Calle 27 De Septiembre",
                            Available = false,
                            Capacity = 500,
                            CreatedAt = new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Municipality = 6,
                            Name = "C.A.M"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SafeMapQROOBackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SafeMapQROOBackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeMapQROOBackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SafeMapQROOBackend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeMapQROOBackend.Models.Occupancy", b =>
                {
                    b.HasOne("SafeMapQROOBackend.Models.Shelter", "Shelter")
                        .WithMany("Occupancy")
                        .HasForeignKey("ShelterId");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("SafeMapQROOBackend.Models.Shelter", b =>
                {
                    b.Navigation("Occupancy");
                });
#pragma warning restore 612, 618
        }
    }
}
